#! /usr/bin/env node

var program = require('commander');
var path = require('path');

program
  .version('0.1.0');

var defaultSuiteFile = path.resolve('tmp/features');
var suite = require(defaultSuiteFile).default;
var n = suite.count;
process.stdout.write(`1..${n}\n`);
suite.run((result) => {
  process.stdout.write(result.tap);
  process.stdout.write('\n');
});
